"""added_user_model

Revision ID: 90be976472d0
Revises: 
Create Date: 2026-07-12 17:19:11.698344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90be976472d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS application')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=10), nullable=False, comment='First Name of Employee'),
    sa.Column('last_name', sa.String(length=10), nullable=False, comment='Last Name of Employee'),
    sa.Column('phone_number', sa.String(length=10), nullable=False, comment='Phone number of Employee'),
    sa.Column('email', sa.String(), nullable=False, comment='Email Address of Employee'),
    sa.Column('position', sa.String(), nullable=False, comment='Position of Employee'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is Employee Active'),
    sa.Column('is_manager', sa.Boolean(), nullable=False, comment='Is Employee Admin'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='application')
    op.execute('DROP SCHEMA IF EXISTS application')
    # ### end Alembic commands ###
