"""added first user model

Revision ID: 9ff9072f1554
Revises: 
Create Date: 2026-07-22 00:21:49.073196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff9072f1554'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS application')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=10), nullable=False, comment='First Name of Employee'),
    sa.Column('last_name', sa.String(length=10), nullable=False, comment='Last Name of Employee'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Password of Employee'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='status_enum', native_enum=False), nullable=False, comment='Status of Employee Anketa'),
    sa.Column('phone_number', sa.String(length=10), nullable=False, comment='Phone number of Employee'),
    sa.Column('email', sa.String(), nullable=False, comment='Email Address of Employee'),
    sa.Column('position', sa.String(), nullable=False, comment='Position of Employee'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Employee Active'),
    sa.Column('is_manager', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Employee Admin'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='application')
    op.execute('DROP SCHEMA IF EXISTS application')
    # ### end Alembic commands ###
